name: stripe_payment_example
description: Demonstrates how to use the stripe_payment plugin.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  stripe_payment:
    path: ../
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
