name: stripe_payment
description: A Flutter plugin to integrate the stripe libraries for iOS and Android. Supports Apple / Google Pay, SCA, PSD2 and much more.
version: 1.0.9
homepage: https://github.com/jonasbark/flutter_stripe_payment

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  json_annotation: ^4.1.0
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.jonasbark.stripe_payment
        pluginClass: StripePaymentPlugin
      ios:
        pluginClass: StripePaymentPlugin

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
